# These are supported funding model platforms

# github: [user1, user2] # Replace with up to 4 GitHub Sponsors-enabled usernames
# patreon: username # Replace with a single Patreon username
# open_collective: username # Replace with a single Open Collective username
# ko_fi: username # Replace with a single Ko-fi username
# tidelift: npm/package-name # Replace with a single Tidelift package
# community_bridge: project-name # Replace with a single Community Bridge project
# liberapay: username # Replace with a single Liberapay username
# issuehunt: username # Replace with a single IssueHunt username
# otechie: username # Replace with a single Otechie username
# lfx_crowdfunding: project-name # Replace with a single LFX Crowdfunding project
# custom: ['https://example.com'] # Replace with up to 4 custom sponsorship URLs
