name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project! Please search existing issues before asking your question.

  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Please provide as much context as possible.
      placeholder: "I'm trying to understand how to..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any additional context, code examples, or screenshots that might help.
    validations:
      required: false
